s="IGCADRPCDIETRNRYTTMOITSRRCCATOOASPHCWIHRPAOPTIHEYIPMYHLLERTEFLTOEPYEURAIRLIHFNTAISFNOAANAPTOSSEOSNNGDSA"
s1=""
for a in range(2,len(s)-1):
    print(a)
    for x in range(0,a):
            s1=s1+s[x::a]
    print (s1)

#CWIHRPAOPTIHEYIPMYHLLERTEFLTOEPYEUR
#AIRLIHFNTAISFNOAANAPTOSSEOSNNGDSA
